-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\untitled\untitled.vhd
-- Created: 2021-08-24 21:36:42
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: untitled
-- Source Path: untitled
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.untitled_pkg.ALL;

ENTITY untitled IS
  PORT( in1                               :   IN    vector_of_std_logic_vector14(0 TO 125);  -- sfix14_En10 [126]
        out1                              :   OUT   vector_of_std_logic_vector14(0 TO 125)  -- sfix14_En13 [126]
        );
END untitled;


ARCHITECTURE rtl OF untitled IS

  -- Component Declarations
  COMPONENT vhdl_approximate_tanh_design_fixpt_slcfg
    PORT( x                               :   IN    vector_of_std_logic_vector14(0 TO 125);  -- sfix14_En10 [126]
          y_out                           :   OUT   vector_of_std_logic_vector14(0 TO 125)  -- sfix14_En13 [126]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : vhdl_approximate_tanh_design_fixpt_slcfg
    USE ENTITY work.vhdl_approximate_tanh_design_fixpt_slcfg(rtl);

  -- Signals
  SIGNAL y_out                            : vector_of_std_logic_vector14(0 TO 125);  -- ufix14 [126]

BEGIN
  u_vhdl_approximate_tanh_design_fixpt_slcfg : vhdl_approximate_tanh_design_fixpt_slcfg
    PORT MAP( x => in1,  -- sfix14_En10 [126]
              y_out => y_out  -- sfix14_En13 [126]
              );

  out1 <= y_out;

END rtl;

