-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Mahsa\Desktop\Th1008_Code\tanh_vhdl_Cordic\codegen\vhdl_approximate_tanh_design\hdlsrc\vhdl_approximate_tanh_design_fixpt_pkg.vhd
-- Created: 2021-08-22 15:32:59
-- 
-- Generated by MATLAB 9.8, MATLAB Coder 5.0 and HDL Coder 3.16
-- 
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE vhdl_approximate_tanh_design_fixpt_pkg IS
  TYPE vector_of_std_logic_vector14 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(13 DOWNTO 0);
  TYPE vector_of_signed14 IS ARRAY (NATURAL RANGE <>) OF signed(13 DOWNTO 0);
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
  TYPE vector_of_signed15 IS ARRAY (NATURAL RANGE <>) OF signed(14 DOWNTO 0);
  TYPE vector_of_signed28 IS ARRAY (NATURAL RANGE <>) OF signed(27 DOWNTO 0);
  TYPE vector_of_signed48 IS ARRAY (NATURAL RANGE <>) OF signed(47 DOWNTO 0);
END vhdl_approximate_tanh_design_fixpt_pkg;

